#!/usr/bin/python3
"""
   factorising the numbers readen from the file into two smaller numbers
"""
from sys import argv


def factorsn(n_from_file):
    """
    Finds the smaller numbers that multiplays to a given number
    """
    x = 2

    if n_from_file < 2:
        return

    while n_from_file % x:
        x += 1
    print("{:.0f}={:.0f}*{:.0f}".format(n_from_file, n_from_file / x, x))


if len(argv) != 2:
    exit()
try:
    with open(argv[1]) as file:
        sel_line = file.readline()

        while sel_line != "":
            n_from_file = int(sel_line.split('\n')[0])
            factorsn(n_from_file)
            sel_line = file.readline()
except:
    pass
